apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-v1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/users
        backend:
          serviceName: echo-server-v1
          servicePort: 80