apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: weton01/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: weton01/product
      context: products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: weton01/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .  
