apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: "prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: weton01/auth:v15
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-aliet-srv:27017/auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: "prod" 
spec:
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
