apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  namespace: "prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: weton01/client
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  namespace: "prod"
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

