apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
  namespace: "prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: weton01/comments:1.0.10
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://comments-mongo-aliet-srv:27017/comments"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
  namespace: "prod" 
spec:
  selector:
    app: comments
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
