apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "aliet-ingress"
  namespace: "prod"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  labels:
    app: aliet-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/users/*
            backend:
              serviceName: auth-srv
              servicePort: 80
          - path: /api/products/*
            backend:
              serviceName: product-srv
              servicePort: 80