apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "aliet-ingress"
  namespace: "prod"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: aliet-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/users/*
            pathType: Prefix
            backend:
              serviceName: auth-srv
              servicePort: 80
          - path: /api/products/*
            pathType: Prefix
            backend:
              serviceName: product-srv
              servicePort: 80