apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: "prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: weton01/product:v16
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://product-mongo-aliet-srv:27017/product"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
  namespace: "prod" 
spec:
  selector:
    app: product
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
