name: deploy-image-auth


on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t weton01/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push weton01/auth
 
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: aliet
          location: us-central1-c
          credentials: ${{ secrets.GKE_SA_KEY }}
          
      - name: rollout deployments
        run: |- 
          kubectl rollout restart deployment/auth
