name: deploy-image-auth


on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t weton01/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push weton01/auth
 
      - uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: aliet
          ZONE_NAME: us-central1-c
        with:
          args: rollout restart deployment/auth
